name: Node CI
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '10.x'
            - run: npm ci
            - run: npm run affected:lint
            - run: npm run affected:build
